# Full 7-neuron hierarchical configuration
server_id: "hal9-full"
neurons:
  # L4 - Strategic Layer
  - id: "neuron-1"
    layer: "L4"
    forward_connections: ["neuron-2", "neuron-3"]
    backward_connections: []
    
  # L3 - Design Layer
  - id: "neuron-2"
    layer: "L3"
    forward_connections: ["neuron-4", "neuron-5"]
    backward_connections: ["neuron-1"]
    
  - id: "neuron-3"
    layer: "L3"
    forward_connections: ["neuron-6", "neuron-7"]
    backward_connections: ["neuron-1"]
    
  # L2 - Implementation Layer
  - id: "neuron-4"
    layer: "L2"
    forward_connections: []
    backward_connections: ["neuron-2"]
    
  - id: "neuron-5"
    layer: "L2"
    forward_connections: []
    backward_connections: ["neuron-2"]
    
  - id: "neuron-6"
    layer: "L2"
    forward_connections: []
    backward_connections: ["neuron-3"]
    
  - id: "neuron-7"
    layer: "L2"
    forward_connections: []
    backward_connections: ["neuron-3"]

# Claude configuration
claude:
  mode: "mock"  # Change to "api" for real Claude
  # api_key: "sk-ant-..."  # Or set ANTHROPIC_API_KEY env var
  model: "claude-3-opus-20240229"
  temperature: 0.7
  max_tokens: 4096
  rate_limit: 60

# Monitoring configuration  
monitoring:
  enabled: true
  metrics_interval: 30
  log_level: "info"