# Server 2 configuration with network enabled
server_id: "hal9-server-2"

# Network configuration for discovery
network:
  enabled: true
  bind_address: "0.0.0.0:9002"
  discovery_enabled: true
  discovery_address: "239.255.42.99:8888"
  discovery_group: "test-cluster"
  max_connections: 100

# Neurons
neurons:
  - id: "neuron-4"
    layer: "L4"
    forward_connections: ["neuron-5", "neuron-6"]
    backward_connections: []
    
  - id: "neuron-5"
    layer: "L3"
    forward_connections: ["neuron-7"]
    backward_connections: ["neuron-4"]
    
  - id: "neuron-6"
    layer: "L3"
    forward_connections: ["neuron-7", "neuron-8"]
    backward_connections: ["neuron-4"]
    
  - id: "neuron-7"
    layer: "L2"
    forward_connections: []
    backward_connections: ["neuron-5", "neuron-6"]
    
  - id: "neuron-8"
    layer: "L2"
    forward_connections: []
    backward_connections: ["neuron-6"]
    
  - id: "neuron-9"
    layer: "L2"
    forward_connections: []
    backward_connections: []
    
  - id: "neuron-10"
    layer: "L3"
    forward_connections: ["neuron-9"]
    backward_connections: []

# Claude configuration
claude:
  mode: "mock"  # Use mock for testing
  model: "claude-3-opus-20240229"
  temperature: 0.7
  max_tokens: 4096
  rate_limit: 60

# Monitoring configuration
monitoring:
  enabled: true
  metrics_interval: 30
  log_level: "info"