# Docker Compose overlay for SSL/TLS support
# Usage: docker-compose -f docker-compose.yml -f docker-compose.ssl.yml up -d

version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: hal9-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - hal9-server
    networks:
      - hal9-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  hal9-server:
    # Override ports - nginx will handle external connections
    ports: []
    expose:
      - "8080"
      - "9090"