apiVersion: apps/v1
kind: Deployment
metadata:
  name: hal9-server
  namespace: hal9
  labels:
    app: hal9-server
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hal9-server
  template:
    metadata:
      labels:
        app: hal9-server
        version: v1
    spec:
      containers:
      - name: hal9-server
        image: hal9/hal9-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: grpc
        - containerPort: 9091
          name: metrics
        env:
        - name: HAL9_ENV
          value: "production"
        - name: RUST_LOG
          value: "info,hal9=debug"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: hal9-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: hal9-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: hal9-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /home/hal9/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: hal9-config
---
apiVersion: v1
kind: Service
metadata:
  name: hal9-server
  namespace: hal9
  labels:
    app: hal9-server
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: grpc
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: metrics
  selector:
    app: hal9-server
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hal9-server-hpa
  namespace: hal9
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hal9-server
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80