{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hal9.fullname" . }}-db-secret
  labels:
    {{- include "hal9.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: |
    {{- if .Values.postgresql.enabled }}
    postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "hal9.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}?sslmode=require
    {{- else }}
    {{ required "A valid database URL is required when not using internal PostgreSQL" .Values.externalDatabase.url }}
    {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hal9.fullname" . }}-redis-secret
  labels:
    {{- include "hal9.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: |
    {{- if .Values.redis.enabled }}
      {{- if .Values.redis.auth.enabled }}
    redis://:{{ .Values.redis.auth.password }}@{{ include "hal9.fullname" . }}-redis-master:6379/0
      {{- else }}
    redis://{{ include "hal9.fullname" . }}-redis-master:6379/0
      {{- end }}
    {{- else }}
    {{ required "A valid Redis URL is required when not using internal Redis" .Values.externalRedis.url }}
    {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hal9.fullname" . }}-jwt-secret
  labels:
    {{- include "hal9.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.security.jwt.secret | b64enc | quote }}
  private-key: {{ .Values.security.jwt.privateKey | b64enc | quote }}
  public-key: {{ .Values.security.jwt.publicKey | b64enc | quote }}
---
{{- if .Values.enterprise.sso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hal9.fullname" . }}-sso-secret
  labels:
    {{- include "hal9.labels" . | nindent 4 }}
type: Opaque
stringData:
  saml-cert: |
{{ .Values.enterprise.sso.saml.certificate | indent 4 }}
  saml-key: |
{{ .Values.enterprise.sso.saml.privateKey | indent 4 }}
  oidc-client-secret: {{ .Values.enterprise.sso.oidc.clientSecret | quote }}
{{- end }}
{{- if .Values.enterprise.encryption.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hal9.fullname" . }}-encryption-secret
  labels:
    {{- include "hal9.labels" . | nindent 4 }}
type: Opaque
data:
  master-key: {{ .Values.enterprise.encryption.masterKey | b64enc | quote }}
  data-key: {{ .Values.enterprise.encryption.dataKey | b64enc | quote }}
{{- end }}
{{- end }}