{{- range $region := .Values.regions.list }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hal9.fullname" $ }}-{{ $region.name }}
  labels:
    {{- include "hal9.labels" $ | nindent 4 }}
    region: {{ $region.name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9001"
    prometheus.io/path: "/metrics"
spec:
  type: {{ $.Values.server.service.type }}
  {{- if $.Values.sessionAffinity.enabled }}
  sessionAffinity: {{ $.Values.sessionAffinity.type }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ $.Values.sessionAffinity.timeoutSeconds }}
  {{- end }}
  ports:
    - port: {{ $.Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ $.Values.server.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "hal9.selectorLabels" $ | nindent 4 }}
    region: {{ $region.name }}
{{- end }}
---
# Global load balancer service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hal9.fullname" . }}
  labels:
    {{- include "hal9.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hal9.selectorLabels" . | nindent 4 }}
---
# Headless service for internal communication
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hal9.fullname" . }}-headless
  labels:
    {{- include "hal9.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hal9.selectorLabels" . | nindent 4 }}