global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hal9-monitor'

scrape_configs:
  # HAL9 Server metrics
  - job_name: 'hal9-server'
    static_configs:
      - targets: ['hal9-server:9091']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Container metrics from cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'

  # PostgreSQL metrics (requires postgres_exporter)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres:5432']
    params:
      query: ['pg_stat_database', 'pg_stat_user_tables']

  # Redis metrics (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

# Alerting rules
rule_files:
  - '/etc/prometheus/alerts/*.yml'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []  # Add alertmanager targets if needed