{{- if .Values.podDisruptionBudget.enabled -}}
{{- range $region := .Values.regions.list }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hal9.fullname" $ }}-{{ $region.name }}-pdb
  labels:
    {{- include "hal9.labels" $ | nindent 4 }}
    region: {{ $region.name }}
spec:
  {{- if $.Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if $.Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ $.Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hal9.selectorLabels" $ | nindent 6 }}
      region: {{ $region.name }}
  {{- if $.Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ $.Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  {{- end }}
{{- end }}
---
# Global PDB for the entire deployment
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hal9.fullname" . }}-global-pdb
  labels:
    {{- include "hal9.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.global.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.global.minAvailable }}
  {{- else }}
  # Ensure at least 50% of pods are available during disruptions
  minAvailable: 50%
  {{- end }}
  selector:
    matchLabels:
      {{- include "hal9.selectorLabels" . | nindent 6 }}
  {{- if .Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ .Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  {{- end }}
{{- end }}