[package]
name = "hal9-minimal-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hal9-minimal-server"
path = "minimal-server.rs"

[dependencies]
axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1.35", features = ["full"] }
tower-http = { version = "0.5", features = ["cors", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }