apiVersion: v2
name: hal9
description: HAL9 Distributed AI Consciousness System
type: application
version: 1.0.0
appVersion: "0.1.0"
keywords:
  - ai
  - distributed
  - consciousness
  - hal9
home: https://github.com/2lab-ai/hal9
sources:
  - https://github.com/2lab-ai/hal9
maintainers:
  - name: HAL9 Team
    email: team@hal9.ai
icon: https://hal9.ai/logo.png
dependencies:
  - name: postgresql
    version: "12.1.9"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.3.14"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: prometheus
    version: "19.0.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.48.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled