[workspace]
resolver = "2"
members = [
    # L2 Implementation - Core neurons
    "layers/L2_implementation/neurons/game_neurons",
    "layers/L2_implementation/neurons/agent_dropout",
    # MCP tools
    "substrate/tooling/mcp/ha-prompter",
    # L8 Visionary implementations
    "layers/L8_visionary/exploration/gentle_singularity",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["HAL9 Team"]
license = "MIT"

[workspace.dependencies]
# Core async runtime
tokio = { version = "1.35", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# Async traits
async-trait = "0.1"

# Common types
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "sqlite", "chrono", "uuid"] }

# Cache
redis = { version = "0.24", features = ["tokio-comp", "connection-manager"] }

# Web framework
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["trace", "cors"] }
hyper = "1.0"

# Async utilities
futures = "0.3"
futures-util = "0.3"

# Concurrent data structures
dashmap = "5.5"
parking_lot = "0.12"

# API
tonic = "0.10"
prost = "0.12"
reqwest = { version = "0.11", features = ["json"] }

# CLI
clap = { version = "4.4", features = ["derive", "env"] }

# Testing
mockall = "0.12"
criterion = { version = "0.5", features = ["html_reports"] }
tokio-test = "0.4"

# Prometheus metrics
prometheus = "0.13"

# GraphQL
async-graphql = { version = "7.0", features = ["apollo_tracing", "apollo_persisted_queries"] }
async-graphql-axum = "7.0"

# Authentication
jsonwebtoken = "9.2"
bcrypt = "0.15"
base64 = "0.21"
rand = "0.8"

# Additional dependencies
once_cell = "1.19"
config = "0.13"
bb8 = "0.8"
bb8-redis = "0.13"
metrics = "0.22"

# External foundation library
gradient-core = { path = "../gradient-core" }